# Generated by Django 2.1.1 on 2018-09-25 19:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookMyClass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 25, 19, 1, 3, 330693, tzinfo=utc)),
        ),
    ]
