# Generated by Django 2.1.1 on 2018-09-25 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookMyClass', '0002_auto_20180926_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
